//Dingel, May 2018
//Labeling variables in Brazilian Census microdata with English descriptions

set more off

cap program drop labels_english
program define labels_english

label variable v0001 "state"
label variable v0002 "city code"
label variable v0011 "weighting area"
label variable v0300 "control number"
label variable v0010 "individual sampling weight"
label variable v1001 "geographic region"
label variable v1002 "meso-region code"
label variable v1003 "micro-region code"
label variable v1004 "metropolitan area code"
label variable v1006 "household setting"
label variable v0502 "relation to the head of household"
label variable v0504 "number associated with the household member"
label variable v0601 "gender"
label variable v6033 "age (years and months)"
label variable v6036 "age in years"
label variable v6037 "age in months (for kids under 1 year-old)"
label variable v6040 "type of declaration of age"
label variable v0606 "race"
label variable v0613 "record of birth"
label variable v0614 "permanent difficulty in seeing"
label variable v0615 "permanent difficulty of hearing"
label variable v0616 "permanent difficulty of walking or stepping up"
label variable v0617 "mental/intellectual permanent disability"
label variable v0618 "born in this city"
label variable v0619 "born in this state"
label variable v0620 "nationality"
label variable v0621 "year took up residence in Brazil"
label variable v0622 "state or country of birth"
label variable v6222 "state of birth codes (see Auxiliary Variables folder - Migra��o_UFs)"
label variable v6224 "country of birth codes (see Auxiliary Variables folder - Migra��o_Pa�ses)"
label variable v0623 "years living in this state uninterruptedly"
label variable v0624 "years living in this municipality uninterruptedly"
label variable v0625 "state and city or country before moving to this municipality"
label variable v6252 "former state of residence"
label variable v6254 "former city of residence"
label variable v6256 "former country of residence"
label variable v0626 "residence on July 31, 2005"
label variable v6262 "state of residence on July 31, 2005"
label variable v6264 "city of residence on July 31, 2005"
label variable v6266 "country of residence on July 31, 2005"
label variable v0627 "knows how to read and write"
label variable v0628 "attending school or daycare"
label variable v0629 "code for school type and educational stage"
label variable v0630 "currently grade/year (elemetary school)"
label variable v0631 "currently grade (high school or above)"
label variable v0632 "conclusion of another undergrad course"
label variable v0633 "highest educational stage attended"
label variable v0634 "conclusion of this educational stage"
label variable v0635 "type of highest educational stage concluded"
label variable v6400 "level of education"
label variable v6352 "undergrad codes (see Auxiliary Variables folder - Cursos Superiores)"
label variable v6354 "master degree codes (see Auxiliary Variables folder - Cursos Mestrado)"
label variable v6356 "doctoral degree codes (see Auxiliary Variables folder - Cursos Doutorado)"
label variable v0636 "city and state or foreign country where attended school"
label variable v6362 "state where attended school codes"
label variable v6364 "city where attended school codes"
label variable v6366 "country where attended school codes"
label variable v0637 "live with spouse or partner"
label variable v0638 "number associated with the spouse or partner"
label variable v0639 "nature of the union"
label variable v0640 "marital status"
label variable v0641 "worked on reference week"
label variable v0642 "were employed but taking time-off during ref. week"
label variable v0643 "helped without pay household member with paid job"
label variable v0644 "worked in cultivation for hhold members sustenance"
label variable v0645 "number of jobs on ref week"
label variable v6461 "occupation codes (see Auxiliary Variables - Ocupa��o)"
label variable v6471 "setor of activity/line of business codes (see CNAEDOM)"
label variable v0648 "in this job were (position in occupation)"
label variable v0649 "how many employees did you have"
label variable v0650 "contributed to social security"
label variable v0651 "type of gross monthly income from main job in july 2010"
label variable v6511 "main job gross monthly income"
label variable v6513 "gross monthly income (including zero income from those who worked in cultivation"
label variable v6514 "income (v6513) in minimum salaries"
label variable v0652 "type of monthly gross income from other jobs"
label variable v6521 "monthly gross income from other jobs"
label variable v6524 "income (v6521) in minimum salaries"
label variable v6525 "income from all jobs"
label variable v6526 "income from all jobs in minimum salaries"
label variable v6527 "total monthly income in july 2010"
label variable v6528 "total monthly income in minimum salaries"
label variable v6529 "household income"
label variable v6530 "household income in minimum salaries"
label variable v6531 "household income per capita"
label variable v6532 "household income per capita in minimum salaries"
label variable v0653 "hours worked weekly on the main job"
label variable v0654 "took any providence to get a job in ref. month"
label variable v0655 "if succeeded to find a job, would have been available to take it in the ref week"
label variable v0656 "in the ref month, had retirement or pension income from social security"
label variable v0657 "in the ref month, had Bolsa-Fam�lia or PETI program income"
label variable v0658 "in the ref month, had other social program or transfer incomes"
label variable v0659 "in the ref month, had income from other sources"
label variable v6591 "in the ref month, what was the total value of this(those) income(s)"
label variable v0660 "in which city and state or country do you work"
label variable v6602 "state codes - work location"
label variable v6604 "city codes - work location"
label variable v6606 "country codes - work location"
label variable v0661 "go back home from work every day"
label variable v0662 "time spent from house to work"
label variable v0663 "had any children born alive until July 31, 2010"
label variable v6631 "male children born alive had until July 31, 2010"
label variable v6632 "female children born alive had until July 31, 2010"
label variable v6633 "total number of children born alive"
label variable v0664 "do you have any children alive on July 31, 2010"
label variable v6641 "male children alive on July 31, 2010"
label variable v6642 "female children alive on July 31, 2010"
label variable v6643 "total number of children alive on July 31, 2010"
label variable v0665 "gender of the last child born alive"
label variable v6660 "age of the last child born alive"
label variable v6664 "had any child born alive in the last 12 months"
label variable v0667 "this child was alive on July 31, 2010"
label variable v0668 "knows the date (at least the year) of the child death"
label variable v6681 "month that the child passed away"
label variable v6682 "year that the child passed away"
label variable v0669 "had any children born dead you until July 31, 2010"
label variable v6691 "male children born dead until July 31, 2010"
label variable v6692 "female children born dead until July 31, 2010"
label variable v6693 "children born dead until July 31, 2010"
label variable v6800 "total number of children born alive and dead"
label variable v0670 "who provided the information about this person"
label variable v0671 "if another household member, number associated with the person who answered"
label variable v6900 "economically active in the week of reference"
label variable v6910 "occupied in the week of reference"
label variable v6920 "situation of occupation in the week of reference"
label variable v6930 "position held in the occupation of the main job"
label variable v6940 "subgroup held on the main job"
label variable v6121 "religion"
label variable v0604 "mother alive"
label variable v0605 "number associated with the mother"
label variable v5020 "number associated with the family"
label variable v5060 "number of family members"
label variable v5070 "family income per capita"
label variable v5080 "family income per capita in minimum salaries"
label variable v6462 "occupation codes - census 2000 compatible"
label variable v6472 "sector of activity codes - census 2000 compatible"
label variable v5110 "contribution to social security in main job"
label variable v5120 "contribution to social security in any job"
label variable v5030 "household composition"
label variable v5040 "existence of a family in the household"
label variable v5090 "type of family - main family"
label variable v5100 "type of family - second family"
label variable v5130 "number associated with the family member"
label variable ano   "survey year"
label variable munic "municipality codes without DV (6 digits)"

end

foreach state in RR AP AC DF RO SE TO MS AM AL MT ES RN PI PB GO PA MA CE SC PE RJ PR RS BA MG SP {
  use "../input/CENSO10_`state'_pes.dta", clear
  labels_english
  save "../output/CENSO10_`state'_pes.dta", replace
}
